spring.application.name=pixzeleria
server.port=8080

# --- CONFIGURACIÓN TEMPORAL H2 (Modo Pruebas) ---
# Simulamos que somos PostgreSQL para que no den error las consultas

spring.datasource.url=jdbc:h2:mem:pixzeleriadb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# Habilitar la consola de H2 (para ver las tablas en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA crea las tablas automáticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/pixzeleria
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


