spring.application.name=pixzeleria

spring.datasource.url=jdbc:postgresql://localhost:5432/pixzeleria
spring.datasource.username=postgres
spring.datasource.password=password

# CREATE hibernate creates db from scratch
# UPDATE hibernate updates db
# NONE : no changes
# VALIDATE para que Hibernate valide que las tablas coincidan con las entidades

spring.jpa.hibernate.ddl-auto=update

# mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# JWT Configuration
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=36000000
# 36000000 ms = 10 hours

management.endpoints.web.exposure.include=mappings