spring.application.name=pixzeleria

# Database Configuration - LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/pixzeleria
spring.datasource.username=postgres
spring.datasource.password=password

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG

# Server port
server.port=8080

# JWT Configuration
jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=36000000

# Debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
management.endpoints.web.exposure.include=mappings